# .env0.yml - env0 configuration file
version: 1

# Variables use Terraform defaults from variables.tf
# Override per environment in env0 UI when needed

# Optional: Custom deployment hooks
# deploy:
#   before:
#     - echo "Starting deployment..."
#   after:
#     - echo "Deployment completed!"

# Optional: Cost policies (requires env0 Pro/Enterprise)
# cost:
#   maxCost: 100